#The JoiintGroupPositionController controls all joints by specifying
#the position with an array of floats. 
arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
   - joint_1
   - joint_2
   - joint_3
   - joint_4
   - joint_5
   - joint_6
